package interpreter;

public enum Token {
	WHILE, IF, WRITE, READ, DO, WEND, SEMICOLON, THEN, 
	ELSE, ENDIF, ASSIGN, PLUS, MINUS, DIV, MULT, MOD,
	LEAST,GREATER, LEAST_EQUAL,GREATER_EQUAL,EQUAL,DIF,
	INT, VAR, ERROR, L_BRACKET, R_BRACKET;
}
