package interpreter;

public enum TokenType {
	WHILE, IF, WRITE, READ, DO, WEND, SEMICOLON, THEN, 
	ELSE, ENDIF, ASSIGN, ARITHMETIC_OPERATOR,
	LOGICAL_OPERATOR, INT, VAR, ERROR, L_PARENTH, R_PARENTH, EOF;
}
